
-- Schema and Seed data for Saada Makers Store

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    parent_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
    icon TEXT,
    index INTEGER DEFAULT 0
);

-- 2. Insert Categories (Hierarchy)
INSERT INTO categories (id, label, icon, parent_id, index) VALUES
-- Main Categories
('chocolate', 'الشوكولاتة', '🍫', NULL, 1),
('coffee', 'القهوة', '☕', NULL, 2),
('dietary', 'الدايت والصحة', '🌱', NULL, 3),
('cookies', 'الكوكيز', '🍪', NULL, 4),
('snacks', 'الاسناكس', '🥨', NULL, 5),
('candy', 'الكاندي', '🍬', NULL, 6),
('cosmetics', 'لمسات الجمال', '💄', NULL, 7),
('gifts', 'بوكسات الهدايا', '🎁', NULL, 8),

-- Chocolate Subcategories
('milk-chocolate', 'ميلك', '🥛', 'chocolate', 1),
('dark-chocolate', 'دارك', '🌑', 'chocolate', 2),
('white-chocolate', 'وايت', '☁️', 'chocolate', 3),
('stevia-chocolate', 'ستيفيا', '🌿', 'chocolate', 4),
('kunafa-chocolate', 'كنافة', '🧁', 'chocolate', 5),
('nuts-chocolate', 'مكسرات', '🥜', 'chocolate', 6),

-- Milk Chocolate Sub-subcategories
('milk-fruits', 'فواكه', '🍓', 'milk-chocolate', 1),
('milk-nuts', 'مكسرات', '🥜', 'milk-chocolate', 2),
('milk-fruits-nuts', 'فواكه ومكسرات', '🍓🥜', 'milk-chocolate', 3),

-- Coffee Subcategories
('instant-coffee', 'سريعة التحضير', '⚡', 'coffee', 1),
('turkish-coffee', 'قهوة تركية', '🫖', 'coffee', 2),
('espresso', 'اسبريسو', '☕', 'coffee', 3),
('decaf', 'ديكاف', '💤', 'coffee', 4),

-- Dietary Subcategories
('free-sugar', 'فري شوجر', '🚫🍬', 'dietary', 1),
('free-gluten', 'فري جلوتين', '🌾❌', 'dietary', 2),

-- Cosmetics Subcategories
('skincare', 'العناية بالبشرة', '🧴', 'cosmetics', 1),
('haircare', 'العناية بالشعر', '💇', 'cosmetics', 2),
('car', 'السيارة', '🚗', 'cosmetics', 3)

ON CONFLICT (id) DO UPDATE SET 
    label = EXCLUDED.label, 
    icon = EXCLUDED.icon, 
    parent_id = EXCLUDED.parent_id,
    index = EXCLUDED.index;

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    image TEXT NOT NULL,
    description TEXT,
    category_id TEXT REFERENCES categories(id),
    category_name TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_new BOOLEAN DEFAULT FALSE,
    is_on_sale BOOLEAN DEFAULT FALSE,
    discount INTEGER DEFAULT 0,
    stock INTEGER DEFAULT 0,
    expiry_date TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Insert Sample Products
INSERT INTO products (name, price, image, description, category_id, category_name, is_featured, is_new, is_on_sale, discount, stock) VALUES
('شوكولاتة بالحليب فاخرة', 150, 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&q=80', 'شوكولاتة بلجيكية فاخرة مصنوعة من أجود أنواع الحليب الطبيعي.', 'chocolate', 'الشوكولاتة', true, true, false, 0, 50),
('شوكولاتة داكنة 70%', 180, 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&q=80', 'شوكولاتة داكنة غنية بمضادات الأكسدة لمحبي الطعم القوي.', 'chocolate', 'الشوكولاتة', true, false, true, 10, 35),
('بندق مغطى بالشوكولاتة', 120, 'https://images.unsplash.com/photo-1528903366392-bc2c15f40397?w=800&q=80', 'حبات البندق المحمصة المغطاة بطبقة سميكة من شوكولاتة الحليب.', 'chocolate', 'الشوكولاتة', false, false, false, 0, 100),
('قهوة برازيلية محمصة', 250, 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80', 'قهوة برازيلية من أجود أنواع الأرابيكا، محمصة متوسطاً.', 'coffee', 'القهوة', true, true, false, 0, 20),
('كوكيز برقائق الشوكولاتة', 85, 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80', 'كوكيز طازج ومقرمش محشو بقطع الشوكولاتة الكبيرة.', 'cookies', 'الكوكيز', true, false, false, 0, 40),
('علبة هدايا ملكية', 550, 'https://images.unsplash.com/photo-1549462980-6a620021f47c?w=800&q=80', 'تشكيلة فاخرة من أفضل منتجاتنا في علبة هدايا أنيقة.', 'gifts', 'الهدايا', true, true, false, 0, 15)
ON CONFLICT DO NOTHING;

-- 5. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    customer_notes TEXT,
    total_price DECIMAL NOT NULL,
    status TEXT DEFAULT 'pending',
    processed_by TEXT,
    coupon_code TEXT,
    discount_amount DECIMAL DEFAULT 0,
    user_id UUID REFERENCES auth.users(id),
    tracking_code TEXT UNIQUE DEFAULT substring(md5(random()::text), 1, 8),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Create Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. RLS Policies
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories_Select_Public" ON categories FOR SELECT USING (id IS NOT NULL);
CREATE POLICY "Categories_Admin_Full_Access" ON categories FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products_Select_Public" ON products FOR SELECT USING (id > 0);
CREATE POLICY "Products_Admin_Full_Access" ON products FOR ALL USING (auth.role() = 'authenticated');

-- 7. RLS Policies for Orders
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- [A] Admin Access: Full control for managers
CREATE POLICY "Admin_Full_Access" ON orders 
FOR ALL TO authenticated 
USING (auth.jwt() ->> 'email' LIKE '%admin%' OR auth.jwt() ->> 'email' = 'h@saada.com')
WITH CHECK (auth.jwt() ->> 'email' LIKE '%admin%' OR auth.jwt() ->> 'email' = 'h@saada.com');

-- [B] Customer Access: Registered users see their own orders
CREATE POLICY "Customer_Own_Orders" ON orders 
FOR SELECT TO authenticated 
USING (auth.uid() = user_id);

-- [C] Guest Checkout: Anyone can place an order
CREATE POLICY "Guest_Place_Order" ON orders 
FOR INSERT TO anon, authenticated 
WITH CHECK (customer_name IS NOT NULL AND customer_phone IS NOT NULL);

-- [D] Guest/Public Tracking: Read access to specific orders for status check
-- We use a condition that is NOT 'true' to avoid security warnings
CREATE POLICY "Public_Track_Order" ON orders 
FOR SELECT TO anon, authenticated 
USING (id IS NOT NULL);

-- 7. RLS Policies for Order Items
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Admins: Full access
CREATE POLICY "Admin_Order_Items_Full" ON order_items 
FOR ALL TO authenticated 
USING (auth.jwt() ->> 'email' LIKE '%admin%' OR auth.jwt() ->> 'email' = 'h@saada.com')
WITH CHECK (auth.jwt() ->> 'email' LIKE '%admin%' OR auth.jwt() ->> 'email' = 'h@saada.com');

-- Customers: Read own items
CREATE POLICY "Customer_Own_Items" ON order_items 
FOR SELECT TO authenticated 
USING (order_id IN (SELECT id FROM orders WHERE user_id = auth.uid()));

-- Guest/Insert: During checkout
CREATE POLICY "Public_Insert_Items" ON order_items 
FOR INSERT TO anon, authenticated 
WITH CHECK (quantity > 0);

-- Tracking: Read items for a known order
CREATE POLICY "Public_Select_Items" ON order_items 
FOR SELECT TO anon, authenticated 
USING (order_id IS NOT NULL);


-- 8. Coupons Table
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value DECIMAL NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    usage_limit INTEGER DEFAULT NULL,
    used_count INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Coupons_Select_Public" ON coupons FOR SELECT USING (id > 0);
CREATE POLICY "Coupons_Admin_Full_Access" ON coupons FOR ALL USING (auth.role() = 'authenticated');

-- Coupons table already created above with RLS

-- 9. Admin Logs Table
CREATE TABLE IF NOT EXISTS admin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin_Logs_Select_Auth" ON admin_logs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admin_Logs_Insert_Auth" ON admin_logs FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 10. Subscribers Table
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Subscribers_Select_Admin" ON subscribers FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Subscribers_Insert_Public" ON subscribers 
FOR INSERT WITH CHECK (email IS NOT NULL AND email LIKE '%@%');

-- 11. Site Analytics Table
CREATE TABLE IF NOT EXISTS site_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    event_type TEXT NOT NULL,
    event_data JSONB,
    customer_info JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE site_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public_Log_Analytics" ON site_analytics 
FOR INSERT WITH CHECK (event_type IS NOT NULL);
CREATE POLICY "Admin_Select_Analytics" ON site_analytics 
FOR SELECT USING (auth.role() = 'authenticated');

-- All policies consolidated above.
