
-- 12. Create Branches Table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    whatsapp_number TEXT NOT NULL,
    latitude DECIMAL NOT NULL,
    longitude DECIMAL NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 13. Create Product Branch Stock Table (Inventory)
CREATE TABLE IF NOT EXISTS product_branch_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    stock INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, branch_id)
);

-- 14. Add branch_id to Orders
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'branch_id') THEN
        ALTER TABLE orders ADD COLUMN branch_id BIGINT REFERENCES branches(id);
    END IF;
END $$;

-- Enable RLS for new tables
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Branches_Select_Public" ON branches;
CREATE POLICY "Branches_Select_Public" ON branches FOR SELECT USING (is_active = TRUE);
DROP POLICY IF EXISTS "Branches_Admin_All" ON branches;
CREATE POLICY "Branches_Admin_All" ON branches FOR ALL USING (TRUE); -- Using simple public access for now since it is development

ALTER TABLE product_branch_stock ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Stock_Select_Public" ON product_branch_stock;
CREATE POLICY "Stock_Select_Public" ON product_branch_stock FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Stock_Admin_All" ON product_branch_stock;
CREATE POLICY "Stock_Admin_All" ON product_branch_stock FOR ALL USING (TRUE); -- Simplified for dev

-- Insert branches
DELETE FROM branches;
INSERT INTO branches (name, whatsapp_number, latitude, longitude) VALUES
('فرع الرحاب', '201050005701', 30.0558637, 31.4913691),
('فرع المهندسين', '201050663537', 30.056319, 31.196222),
('فرع المعادي 1', '201050663538', 29.962696, 31.276942),
('فرع المعادي 2', '201050006956', 29.9640, 31.2740),
('فرع مدينة نصر', '201050006929', 30.061883, 31.345014),
('فرع مصر الجديدة', '201050006946', 30.1000, 31.3333),
('فرع اسكندرية', '201050663539', 31.2458, 29.9660);
