
-- Schema and Seed data for Saada Makers Store

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

-- 2. Insert Categories
INSERT INTO categories (id, label) VALUES
('chocolate', 'الشوكولاتة'),
('coffee', 'القهوة'),
('cookies', 'الكوكيز'),
('candy', 'الكاندي'),
('snacks', 'الاسناكس'),
('gifts', 'الهدايا')
ON CONFLICT (id) DO NOTHING;

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    image TEXT NOT NULL,
    description TEXT,
    category_id TEXT REFERENCES categories(id),
    category_name TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_new BOOLEAN DEFAULT FALSE,
    is_on_sale BOOLEAN DEFAULT FALSE,
    discount INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Insert Sample Products
INSERT INTO products (name, price, image, description, category_id, category_name, is_featured, is_new, is_on_sale, discount) VALUES
('شوكولاتة بالحليب فاخرة', 150, 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&q=80', 'شوكولاتة بلجيكية فاخرة مصنوعة من أجود أنواع الحليب الطبيعي.', 'chocolate', 'الشوكولاتة', true, true, false, 0),
('شوكولاتة داكنة 70%', 180, 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&q=80', 'شوكولاتة داكنة غنية بمضادات الأكسدة لمحبي الطعم القوي.', 'chocolate', 'الشوكولاتة', true, false, true, 10),
('بندق مغطى بالشوكولاتة', 120, 'https://images.unsplash.com/photo-1528903366392-bc2c15f40397?w=800&q=80', 'حبات البندق المحمصة المغطاة بطبقة سميكة من شوكولاتة الحليب.', 'chocolate', 'الشوكولاتة', false, false, false, 0),
('قهوة برازيلية محمصة', 250, 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80', 'قهوة برازيلية من أجود أنواع الأرابيكا، محمصة متوسطاً.', 'coffee', 'القهوة', true, true, false, 0),
('كوكيز برقائق الشوكولاتة', 85, 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80', 'كوكيز طازج ومقرمش محشو بقطع الشوكولاتة الكبيرة.', 'cookies', 'الكوكيز', true, false, false, 0),
('علبة هدايا ملكية', 550, 'https://images.unsplash.com/photo-1549462980-6a620021f47c?w=800&q=80', 'تشكيلة فاخرة من أفضل منتجاتنا في علبة هدايا أنيقة.', 'gifts', 'الهدايا', true, true, false, 0);

-- 5. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    customer_notes TEXT,
    total_price DECIMAL NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Create Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. RLS Policies (Enable Read for everyone)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select on categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public insert on categories" ON categories FOR INSERT WITH CHECK (true);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select on products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public insert on products" ON products FOR INSERT WITH CHECK (true);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert on orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on orders" ON orders FOR SELECT USING (true);

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert on order_items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on order_items" ON order_items FOR SELECT USING (true);
